### ISSUE TITLE
IndexError: index 19744 is out of bounds for axis 0 with size 17100

### ISSUE THREAD

**Issue by summerrr** [engineer1109/TensorFlow-R-FCN-for-primary-students#3]
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/user10/notebook/TensorFlow-R-FCN-for-primary-students/tools/../lib/layer_utils/proposal_layer.py", line 39, in proposal_layer
    proposals = proposals[order, :]

IndexError: index 19744 is out of bounds for axis 0 with size 17100
I use vgg16，do you know how to solve it？
and I use res101，it will occur “tensorflow.python.framework.errors_impl.InternalError: CUB segmented reduce errorinvalid configuration argument”

**Comment by thienlong95z** [comment]
have you solved that error?
