### ISSUE TITLE
 No module named cython_nms

### ISSUE THREAD

**Issue by summerrr** [engineer1109/TensorFlow-R-FCN-for-primary-students#5]
user10@Gpu1:~/notebook/TensorFlow-R-FCN-for-primary-students$ sh run
Traceback (most recent call last):
  File "./tools/demo2.py", line 12, in <module>
    from model.test import im_detect
  File "/home/user10/notebook/TensorFlow-R-FCN-for-primary-students/tools/../lib/model/test.py", line 20, in <module>
    from utils.cython_nms import nms, nms_new
ImportError: No module named cython_nms
do you know why？I make and have these files in lib/utils ,whether I lack something?
bbox.c          cython_bbox.cpython-35m-x86_64-linux-gnu.so  nms.pyc
bbox.pyx        cython_nms.cpython-35m-x86_64-linux-gnu.so   nms.pyx
blob.py         __init__.py                                  __pycache__
blob.pyc        __init__.pyc                                 timer.py
boxes_grid.py   nms.c                                        timer.pyc
boxes_grid.pyc  nms.py

**Comment by engineer1109** [comment]
Under ./lib
make

**Comment by noopur2805** [comment]
How did you solve this error?
